---
- name: install /etc/elasticsearch/elasticsearch.yml
  become: yes
  become_user: root
  template: >-
    src=etc/elasticsearch/elasticsearch.yml.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    mode=0644

- name: starting up elasticsearch...
  when: elasticsearch_launch
  include: '{{elasticsearch_supervisor}}.yml'

