---
- name: install elasticsearch.yml
  become: yes
  become_user: root
  with_items:
    - f: elasticsearch.yml
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d|default("/etc/elasticsearch")}}/{{item.f}}'
    mode: '{{item.m|default("0644")}}'

- include: '{{elasticsearch_supervisor|default("systemd")}}.yml'

